name: ci
on:
  push: { branches: [main] }
  pull_request: { branches: [main] }
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Basic repo sanity
        run: |
          test -s README.md
          test -s docs/day10-12.md
          echo "OK"
